### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by eigenvivek** [Pragyanstha/SCR-Registration#1]
Hi @Pragyanstha , very interesting work! Do you know when the code will be made available? Thank you.

**Comment by springXIACJ** [comment]
Hi @Pragyanstha  , very interesting in the  Scene Coordinate Regression Model! Do you know when the code will be made available? Thank you.

**Comment by Pragyanstha** [comment]
@springXIACJ  @eigenvivek 
Thanks for the interest and sorry for the delay, I will make the code for SCR model available by next week.

**Comment by springXIACJ** [comment]
Thanks for the source code. Can you provide the code for model training?
